version: 2.1

orbs:
  node: circleci/node@7.1.0

jobs:
  code-review:
    docker:
      - image: cimg/openjdk:17.0-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run:
          name: Install Dependencies
          command: . scripts/bash/install_dependencies.sh
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run Code Analyzer
          command: . scripts/bash/run_code_scanner.sh
      - store_artifacts:
          path: staticCodeAnalysis.json

workflows:
  sfdx-workflow:
    jobs:
      - code-review:
          filters:
            branches:
              only:
                - /^feature\/.+/