# single config.yml required for non GitHub App integration pipelines; deprecated for this project
version: 2.1

orbs:
  jq: circleci/jq@3.0.2
  node: circleci/node@7.1.0

jobs:
  create-package-version:
    executor: node/default
    steps:
      - checkout
      - jq/install
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run:
          name: Install Dependencies
          command: . scripts/bash/install_dependencies.sh
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Login to Dev Hub Org
          command: . scripts/bash/login_devhub_org.sh
      - run:
          name: Create Package Version
          command: . scripts/bash/create_package_version.sh
      - store_artifacts:
          path: loginDevHubResults.json
      - store_artifacts:
          path: packageVersionCreateResults.json
      - store_artifacts:
          path: packageVersionReport.json

  install-package-version:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run:
          name: Install Dependencies
          command: . scripts/bash/install_dependencies.sh
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Login to Build Org
          command: . scripts/bash/login_build_org.sh
      - run:
          name: Create Package Version
          command: . scripts/bash/install_package_version.sh
      - store_artifacts:
          path: loginBuildResults.json
      - store_artifacts:
          path: packageVersionInstallationResults.json

  code-review:
    docker:
      - image: cimg/openjdk:17.0-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run:
          name: Install Dependencies
          command: . scripts/bash/install_dependencies.sh
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: SFDX Scanner Analysis
          command: . scripts/bash/run_pmd_code_scanner.sh
      - store_artifacts:
          path: codeScannerAnalysis.json

  validate-deploy-test:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run:
          name: Install Dependencies
          command: . scripts/bash/install_dependencies.sh << pipeline.git.branch >>
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Login to Dev Hub Org
          command: . scripts/bash/login_devhub_org.sh
      - run:
          name: Request Scratch Org
          command: . scripts/bash/request_scratch_org.sh
      - run:
          name: Validate Deployment w/Local Tests
          command: . scripts/bash/validate_deploy_apex_tests.sh
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: loginDevHubResults.json
      - store_artifacts:
          path: activeScratchOrgQueryResults.json
      - store_artifacts:
          path: scratchOrgCreateResults.json
      - store_artifacts:
          path: loginScratchResults.json
      - store_artifacts:
          path: validateDeployResults.json

workflows:
  sfdx-workflow:
    jobs:
      - code-review:
          filters:
            branches:
              only:
                - /^feature\/.+/

      - validate-deploy-test:
          filters:
            branches:
              only:
                - /^feature\/.+/
                - develop

      - create-package-version:
          filters:
            branches:
              only:
                - /^release\/+v[0-9]+\.[0-9]+\.[0-9]+$/

      - install-package-version:
          requires:
            - create-package-version
          filters:
            branches:
              only:
                - /^release\/+v[0-9]+\.[0-9]+\.[0-9]+$/
