version: 2.1

orbs:
  jq: circleci/jq@3.0.2
  node: circleci/node@7.1.0

jobs:
  validate-deploy-test:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run:
          name: Install Dependencies
          command: . scripts/bash/install_dependencies.sh << pipeline.git.branch >>
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Login to Dev Hub Org
          command: . scripts/bash/login_devhub_org.sh
      - run:
          name: Request Scratch Org
          command: . scripts/bash/request_scratch_org.sh
      - run:
          name: Validate Deployment w/Local Tests
          command: . scripts/bash/validate_deploy_apex_tests.sh
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: loginDevHubResults.json
      - store_artifacts:
          path: activeScratchOrgQueryResults.json
      - store_artifacts:
          path: scratchOrgCreateResults.json
      - store_artifacts:
          path: loginScratchResults.json
      - store_artifacts:
          path: validateDeployResults.json

workflows:
  sfdx-workflow:
    jobs:
      - validate-deploy-test:
          filters:
            branches:
              only:
                - /^feature\/.+/
                - develop